### ISSUE TITLE
rpc-secure

### ISSUE THREAD

**Issue by viharm** [shiny/php-aria2#1]
This is a very good class, and extremely easy to use. Thank you.

I am building a web interface and would like to encrypt traffic between the web ui and Aria2 via the RPC interface.

Does this class provide capability to connect to Aria2 via secure rpc (https)?

Thanks in advance.

Regards.

**Comment by shiny** [comment]
Initialize this class with https url will works.

 But on some server, certificate's verification may be failed.

So,add this line would be better:
`curl_setopt($this->ch, CURLOPT_CAINFO, '/path/to/cacert.pem');`

**Comment by viharm** [comment]
Thanks for this information. I read more about it and tried inserting this into the class, both before and after `curl_setopt_array`. I also tried including it in the array data, but I am failing to make it work. Is there a way to debug the class? I don't see any PHP errors.

I have also checked file permissions and the CA cert permissions are u=rw,g=r,o=r, so both aria2 and www-data user should be able to read the file.

I am running Apache 2.2.22-13+deb7u4 with PHP 5.4.39-0+deb7u2 on Debian Wheezy 7.8 with Aria2 1.18.8-1 from the Jessie repository.

**Comment by shiny** [comment]
I have to admit that this class is too simple.😄
if curl_exec returned data === false, should call `curl_error` to get error info for details.
Because the manual says,  if the CURLOPT_RETURNTRANSFER option is set, it will return the result on success, FALSE on failure.

a simple example(not tested)

```
    private function req($data) 
    {
        curl_setopt($this->ch, CURLOPT_POSTFIELDS, $data);
        $data = curl_exec($this->ch);
        if ($data===false)  {
            $error_message = curl_error($this->ch);
            $error_no = curl_errno($this->ch);
            throw new Exception($error_message, $error_no);
        }
        return $data;
    }
```

**Comment by shiny** [comment]
I can't enable secure rpc successfully so that I can't test my code.  😂

If you can send me a pack with self-signed certificate and let aria2 start secure RPC, I will improve this class's ssl support.

**Comment by viharm** [comment]
Thanks for the follow up. I believe that your `if` condition was too strict. I tried the following

``` php
    private function req ( $data ) {
      curl_setopt ( $this -> ch , CURLOPT_POSTFIELDS , $data ) ;
      $result = curl_exec($this->ch);

      if (!$result )  {
        trigger_error(curl_error($this->ch)); 
      }

      return $result ;
    }
```

Also set PHP options:

``` php
 ini_set('display_errors', 1);
 error_reporting(E_ALL);
```

Without the `CURLOPT_CAINFO` option I get the following **notice**:

```
Notice: SSL certificate problem: unable to get local issuer certificate
```

When I add:

``` php
$curlstat = curl_setopt($this->ch,  CURLOPT_CAINFO , '/path/to/sub.class1.server.ca.pem' );
```

I get the following:

```
Notice: error setting certificate verify locations: CAfile: /path/to/sub.class1.server.ca.pem CApath: /path/only
```

I had a problem getting `rpc-secure` in _Aria2_ working too. Found that it was not available in v1.15 which ships with _Debian Wheezy._

I came across http://jsonrpcphp.org/, but not sure if it will work. They use `fopen` instead of `curl_exec`. What do you think?

**Comment by shiny** [comment]
Using === is a good practice if you are sure what it returns.
My Aria2 version 1.18.9 on OS X not works well.

open will works well even cURL is not installed. But I'm worried about it's SSL compatibility.
cURL is recommended.

**Comment by viharm** [comment]
You are absolutely right on both counts.

`===` is very robust, but I have seen that PHP uses integers `0` and `1` for boolean values `true` and `false` respectively; so reducing its strictness sometimes helps with debugging.

I tried using the _phpjsonrpc_ but it does not work with `secure-rpc`.

I will be happy to offer an instance of _Aria2_ with `secure-rpc`, to help you improve _php-aria2_'s SSL capability, as you offered.

Could you please explain how I can send you a pack with self-signed certificate to help with this?

**Comment by viharm** [comment]
OK, I saw some progress in the troubleshooting. I was getting one of three errors:

```
60 : SSL certificate problem: unable to get local issuer certificate
51 : SSL peer certificate or SSH remote key was not OK
77 : error setting certificate verify locations
```

I got it working, but had to disable certificate verification.

``` php
curl_setopt($this->ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($this->ch, CURLOPT_SSL_VERIFYHOST, false);
```

However this is not secure. So although the script works OK, it is either the curl framework or a problem in SSL that is causing this.

**Comment by shiny** [comment]
OK send the pack to  daijie@php.net please. And with your OS/aria2 version details. Thank you!
I think `curl_setopt($this->ch, CURLOPT_SSL_VERIFYPEER, false);` is not a good idea. :)

**Comment by viharm** [comment]
Sure, happy to help. Could you please help me to understand how I can package self-signed to send you, and which ones I need to configure in Aria2 for this?

**Comment by shiny** [comment]
`aria2c --enable-rpc --rpc-secure=true --rpc-certificate= <FILE>  --rpc-private-key=<FILE>`
aria2c can't recognize my certificate.
How about yours?

**Comment by viharm** [comment]
Hi, I have enabled _Aria2_ with secure RPC using self-signed certificates. Looks like it works (see _Aria2_ log file)

```
2015-05-03 15:25:47.958046 [NOTICE] [DownloadEngineFactory.cc:202] RPC transport will be encrypted.
2015-05-03 15:25:47.958172 [NOTICE] [HttpListenCommand.cc:111] IPv4 RPC: listening on TCP port 6800
```

| Software | Detail |
| --- | --- |
| _Aria2_ version | 1.18.8-1 |
| OS | Debian Wheezy 7.8 |
| Architecture | x86-64 |

I have sent you connection details privately by e-mail. Please advise if you require further information or assistance for this.

**Comment by viharm** [comment]
Any updates so far?

**Comment by viharm** [comment]
Had some intermittent temporary issues with the VM this test is running on. It is all back online.

**Comment by viharm** [comment]
Hi, I forked and added some debugging to the code using Kint (https://github.com/raveren/kint); which helped me identify that the issue was in the CA certificate. cURL works fine with Aria2 via Secure RPC. Happy to provide you with the deb-enabled version if you wish, but it is not as beautiful and simple is your's :smiley: :satisfied:

**Comment by shiny** [comment]
Sorry for the delay,those days I'm busy with my work.
I have tried and succeed.
1. This code already works well if your certificate is issued by famous providers ,such as alphassl. just `new aria2("https://YOUR-DOMAIN:6800/jsonrpc");`
2. Or it will say "SSL certificate problem: unable to get local issuer certificate", 
   You should provide a ca certificate (chain file),
   and set in `curl_setopt($this->ch, CURLOPT_CAINFO, __DIR__.'/ca.crt');`
3. I don't know how to work with self-signed certificate yet.

A simple example supports ca certificate

```
<?php
class aria2
{
    protected $server;
    protected $ch;

    function __construct($server='http://127.0.0.1:6800/jsonrpc', $ca=null)
    {
        $this->server = $server;
        $this->ch = curl_init($server);
        if(!is_null($ca)) {
            curl_setopt($this->ch, CURLOPT_CAINFO, stream_resolve_include_path($ca));
        }
        curl_setopt_array($this->ch, array(
            CURLOPT_POST=>true,
            CURLOPT_RETURNTRANSFER=>true,
            CURLOPT_HEADER=>false
        ));
    }

    function __destruct()
   {
        curl_close($this->ch);
    }

    protected function req($data)
    {
        curl_setopt($this->ch, CURLOPT_POSTFIELDS, $data);        
        return curl_exec($this->ch);
    }

    function __call($name, $arg)
    {
        $data = array(
            'jsonrpc'=>'2.0',
            'id'=>'1',
            'method'=>'aria2.'.$name,
            'params'=>$arg
        );
        $data = json_encode($data);
        $res = $this->req($data);
        if($res===false) {
            trigger_error(curl_error($this->ch));
        }
        return json_decode($res, 1);
    }
}
```

test.php:

```
<?php
    require('aria2.class.php');
    $aria2 = new aria2("https://cn.jarfire.org:6800/jsonrpc", "wosign.crt");
    var_dump($aria2->getGlobalStat());
```

running aria2:

```
 aria2c --enable-rpc --rpc-certificate=/etc/apache2/ssl/jarfire.pem --rpc-private-key=/etc/apache2/ssl/jarfire.key --rpc-secure  --rpc-listen-all
```

**Comment by shiny** [comment]
It seems aria2c json-rpc can't set ca certificate like apache?

**Comment by shiny** [comment]
https://letsencrypt.org/ is coming soon 😀

**Comment by viharm** [comment]
Understood most of it. Passing the CA file is a good solution. However I did not completely understand the use of `stream_resolve_include_path`. Does it assume that the CA file resides in the same directory as the script? I tried the PHP website but could not fully understand its use. I want to understand because I wish to extend _php-aria2_ to include some user-friendly features (https://github.com/viharm/phpAria2rpc).

Yes, you are right, Aria2 does not set CA. It assumes that it is the client's responsibility to verify certificate validity (this is not the worst). Probably another good reason that `curl` is the better option.

I tend to use free server certificates from [StartSSL](https://www.startssl.com/). 

I am new to _Let's Encrypt_. It looks very interesting. Thanks for the link.

**Comment by shiny** [comment]
stream_resolve_include_pat:Resolve filename against the include path. 
because CURLOPT_CAINFO need a absolute path.
May be StartSSL needs ca cert.

**Comment by shiny** [comment]
I tested StartSSL.
ca cert of StartSSL is `https://www.startssl.com/certs/ca-bundle.pem`
A simple example:

```
<?php
require('aria2.class.php');
$aria2 = new aria2("https://hongkong.meettea.com:6800/jsonrpc", 'ca-bundle.pem');
var_dump($aria2->getGlobalStat());
```

**Comment by viharm** [comment]
Yes, _StartSSL_ is a bit known and much better than self-signed certificates; however there are some limitations on the free services.

Thanks for the update. The new function looks good and I want to include in my fork of this library.

I am intrigued that by using `stream_resolve_include_path`, you only specify the file name as a parameter and not the entire path. Where do you actually save the file? How does the function find the file?

**Comment by shiny** [comment]
I place the file near the php file(in the same dir). 
It has the same rules as `include`.
You can use `realpath` as replacement.
It's only my personal habit. 😏

**Comment by viharm** [comment]
OK, thanks for the clarification. I have updated my fork with the primary changes. I would like to know what you think, if you get the time.

I will close this thread. Thanks for your support and the new information.
