### ISSUE TITLE
addUri with pre defined id

### ISSUE THREAD

**Issue by Anan5a** [shiny/php-aria2#3]
Is it possible to set a predefined id to a download request?
also retrive the status using that id?

**Comment by shiny** [comment]
> Is it possible to set a predefined id to a download request?
> also retrive the status using that id?

Yes, example below
```php
$aria2 = new Aria2('http://127.0.0.1:6800/jsonrpc'); 
$customGidPrefix = '1111';
$customGid = "${customGidPrefix}111111111111";
var_dump($aria2->addUri(
	['https://www.google.com.hk/images/srpr/logo3w.png'],
	[
		'dir'=>'/tmp',
		'gid'=>$customGid
	]
));
var_dump($aria2->tellStatus($customGid));
var_dump($aria2->tellStatus($customGidPrefix));
```

> The GID must be **hex string of 16 characters,** thus [0-9a-fA-F] are allowed and leading zeros must not be stripped. The GID all 0 is reserved and must not be used. **The GID must be unique**, otherwise error is reported and the download is not added. 

Aria2 would return an error message `No URI to download.` if you did not provided a correct Gid.

All the other options for `aria2.addUri`, same as `Input File`: https://aria2.github.io/manual/en/html/aria2c.html?highlight=adduri#id2
